import React, { useState, useEffect } from 'react';
import { Category, Transaction, TransactionType } from '../types';
import { INCOME_CATEGORIES, EXPENSE_CATEGORIES } from '../constants';
import { detectCategory } from '../utils/categoryRules';

// UUID generator only for installment grouping now
const generateGroupId = () => crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2, 15);

interface TransactionModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (transactions: Transaction[]) => void;
  initialType?: TransactionType; // New prop to set initial state
}

export const TransactionModal: React.FC<TransactionModalProps> = ({ 
  isOpen, 
  onClose, 
  onSave,
  initialType = TransactionType.EXPENSE 
}) => {
  const [description, setDescription] = useState('');
  const [amount, setAmount] = useState('');
  const [type, setType] = useState<TransactionType>(initialType);
  const [category, setCategory] = useState<Category>(Category.FOOD);
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  
  const [isFixed, setIsFixed] = useState(false);
  const [isInstallment, setIsInstallment] = useState(false);
  const [installments, setInstallments] = useState(2);

  // Effect to reset form and set correct type when modal opens
  useEffect(() => {
    if (isOpen) {
      handleTypeChange(initialType);
      resetFormFields();
    }
  }, [isOpen, initialType]);

  // AUTO-CATEGORIZATION LOGIC
  useEffect(() => {
    if (!description) return;
    
    const detected = detectCategory(description);
    if (detected) {
      // Only verify if the detected category belongs to the current type (Income vs Expense)
      const isIncomeCat = INCOME_CATEGORIES.includes(detected);
      const isExpenseCat = EXPENSE_CATEGORIES.includes(detected);

      if (type === TransactionType.INCOME && isIncomeCat) {
        setCategory(detected);
      } else if (type === TransactionType.EXPENSE && isExpenseCat) {
        setCategory(detected);
      }
    }
  }, [description, type]);

  if (!isOpen) return null;

  // Helper to switch type and reset category to a valid default
  const handleTypeChange = (newType: TransactionType) => {
    setType(newType);
    if (newType === TransactionType.INCOME) {
      setCategory(Category.SALARY);
      setIsFixed(false);
      setIsInstallment(false);
    } else {
      setCategory(Category.FOOD);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const numAmount = parseFloat(amount);
    if (!description || isNaN(numAmount)) return;

    const newTransactions: Transaction[] = [];
    // We append a time to ensure timezone consistency doesn't shift the day when converting back/forth
    const startDate = new Date(date + 'T12:00:00');

    if (type === TransactionType.EXPENSE && isInstallment) {
      // Logic for installments
      const installmentAmount = numAmount / installments;
      const groupId = generateGroupId();

      for (let i = 0; i < installments; i++) {
        const currentDate = new Date(startDate);
        currentDate.setMonth(startDate.getMonth() + i);
        
        newTransactions.push({
          // id is auto-generated by DB
          description: `${description} (${i + 1}/${installments})`,
          amount: installmentAmount,
          type: type,
          category: category,
          date: currentDate.toISOString().split('T')[0],
          isInstallment: true,
          installmentGroupId: groupId,
          currentInstallment: i + 1,
          totalInstallments: installments,
          isFixed: false
        });
      }
    } else if (type === TransactionType.EXPENSE && isFixed) {
      // NEW LOGIC: Fixed Expenses (Generate 12 months ahead)
      // This ensures it shows up in next months automatically
      const groupId = generateGroupId();

      for (let i = 0; i < 12; i++) {
        const currentDate = new Date(startDate);
        currentDate.setMonth(startDate.getMonth() + i);

        newTransactions.push({
          description: description, 
          amount: numAmount,
          type: type,
          category: category,
          date: currentDate.toISOString().split('T')[0],
          isInstallment: false,
          isFixed: true,
          originalId: groupId
        });
      }
    } else {
      // Single, one-time transaction
      newTransactions.push({
        description,
        amount: numAmount,
        type,
        category,
        date,
        isInstallment: false,
        isFixed: false, 
      });
    }

    onSave(newTransactions);
    onClose();
  };

  const resetFormFields = () => {
    setDescription('');
    setAmount('');
    setDate(new Date().toISOString().split('T')[0]);
    setIsFixed(false);
    setIsInstallment(false);
    setInstallments(2);
  };

  const availableCategories = type === TransactionType.INCOME ? INCOME_CATEGORIES : EXPENSE_CATEGORIES;
  const dateLabel = (type === TransactionType.EXPENSE && isInstallment) ? "Data 1ª Parc." : "Data";

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-60 backdrop-blur-sm p-4 animate-fade-in">
      <div className="bg-white rounded-3xl w-full max-w-sm shadow-2xl overflow-hidden animate-scale-up">
        <div className={`flex justify-between items-center p-5 border-b ${type === TransactionType.INCOME ? 'bg-green-50 border-green-100' : 'bg-red-50 border-red-100'}`}>
          <h2 className={`text-lg font-bold ${type === TransactionType.INCOME ? 'text-green-800' : 'text-red-800'}`}>
            {type === TransactionType.INCOME ? 'Nova Receita' : 'Nova Despesa'}
          </h2>
          <button onClick={onClose} className="bg-white rounded-full p-1 shadow-sm text-slate-400 hover:text-slate-600 active:scale-90 transition-all">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
          </button>
        </div>
        
        <form onSubmit={handleSubmit} className="p-5 space-y-4">
          
          {/* Type Toggle */}
          <div className="flex bg-slate-100 p-1.5 rounded-2xl">
            <button
              type="button"
              onClick={() => handleTypeChange(TransactionType.INCOME)}
              className={`flex-1 py-2 text-sm font-bold rounded-xl transition-all ${type === TransactionType.INCOME ? 'bg-white text-green-600 shadow-sm' : 'text-slate-400'}`}
            >
              Receita
            </button>
            <button
              type="button"
              onClick={() => handleTypeChange(TransactionType.EXPENSE)}
              className={`flex-1 py-2 text-sm font-bold rounded-xl transition-all ${type === TransactionType.EXPENSE ? 'bg-white text-red-600 shadow-sm' : 'text-slate-400'}`}
            >
              Despesa
            </button>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1.5">Descrição</label>
            <input
              required
              type="text"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all text-sm font-medium"
              placeholder={type === TransactionType.INCOME ? "Ex: Salário" : "Ex: Mercado"}
            />
            {description && (
                <p className="text-[10px] text-slate-400 mt-1 text-right">
                    Sugestão: <span className="font-semibold text-blue-500">{category}</span>
                </p>
            )}
          </div>

          <div className="flex gap-3">
            <div className="flex-1">
              <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1.5">Valor</label>
              <input
                required
                type="number"
                step="0.01"
                min="0.01"
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none font-bold text-slate-800"
                placeholder="0,00"
              />
            </div>
            <div className="flex-1">
              <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1.5">{dateLabel}</label>
              <input
                required
                type="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-sm text-slate-600"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wide mb-1.5">Categoria</label>
            <div className="relative">
              <select
                value={category}
                onChange={(e) => setCategory(e.target.value as Category)}
                className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none appearance-none text-sm text-slate-700 font-medium"
              >
                {availableCategories.map((cat) => (
                  <option key={cat} value={cat}>{cat}</option>
                ))}
              </select>
              <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-slate-400">
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m6 9 6 6 6-6"/></svg>
              </div>
            </div>
          </div>

          {type === TransactionType.EXPENSE && (
            <div className="space-y-3 pt-2">
               <div className="flex items-center justify-between bg-slate-50 p-3 rounded-xl">
                <label className="flex items-center text-sm text-slate-700 cursor-pointer font-medium">
                  <input
                    type="checkbox"
                    checked={isInstallment}
                    onChange={(e) => {
                      setIsInstallment(e.target.checked);
                      if(e.target.checked) setIsFixed(false);
                    }}
                    className="w-5 h-5 text-blue-600 rounded focus:ring-blue-500 border-slate-300"
                  />
                  <span className="ml-3">Parcelado?</span>
                </label>
                {isInstallment && (
                    <input
                        type="number"
                        min="2"
                        max="48"
                        value={installments}
                        onChange={(e) => setInstallments(parseInt(e.target.value))}
                        className="w-16 px-2 py-1 text-center border border-blue-200 rounded-lg focus:outline-none focus:border-blue-400 text-sm font-bold text-blue-600"
                    />
                )}
              </div>

              {!isInstallment && (
                  <div className="flex items-center justify-between bg-slate-50 p-3 rounded-xl">
                    <label className="flex items-center text-sm text-slate-700 cursor-pointer font-medium">
                    <input
                        type="checkbox"
                        checked={isFixed}
                        disabled={isInstallment}
                        onChange={(e) => setIsFixed(e.target.checked)}
                        className="w-5 h-5 text-blue-600 rounded focus:ring-blue-500 border-slate-300 disabled:opacity-50"
                    />
                    <span className="ml-3">Despesa Fixa?</span>
                    </label>
                </div>
              )}
            </div>
          )}

          <div className="pt-2">
            <button
              type="submit"
              className={`w-full text-white font-bold py-3.5 rounded-2xl transition-all shadow-lg active:scale-95 ${type === TransactionType.INCOME ? 'bg-green-500 hover:bg-green-600 shadow-green-200' : 'bg-red-500 hover:bg-red-600 shadow-red-200'}`}
            >
              Confirmar
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};